// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT-l481XWfC5USYBoXzWwxPSZxmfc5ucE',
    appId: '1:153355691909:web:8ea9ed30df298e72ed46ec',
    messagingSenderId: '153355691909',
    projectId: 'dynamiclinks-aaf2b',
    authDomain: 'dynamiclinks-aaf2b.firebaseapp.com',
    storageBucket: 'dynamiclinks-aaf2b.appspot.com',
    measurementId: 'G-C880LN892M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYuvAE2dUjecRxZQPrl8lB2ELSTDd664',
    appId: '1:153355691909:android:189ff3540799bff2ed46ec',
    messagingSenderId: '153355691909',
    projectId: 'dynamiclinks-aaf2b',
    storageBucket: 'dynamiclinks-aaf2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FmOLGBR3fwEJzuEZ-XlQ781RKpmOSu0',
    appId: '1:153355691909:ios:ce98010ca0f5c028ed46ec',
    messagingSenderId: '153355691909',
    projectId: 'dynamiclinks-aaf2b',
    storageBucket: 'dynamiclinks-aaf2b.appspot.com',
    iosClientId: '153355691909-7jm3g5vf5oa8tov6r88ur3gq6158vtu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplinkTutorial',
  );
}
